/**
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebarJSBolt: [
    {
      type: 'html',
      value: '<h3>Bolt for JavaScript</h3>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    'getting-started',
    {
      type: 'category',
      label: 'Basic concepts',
      items: [
        'basic/message-listening',
        'basic/message-sending',
        'basic/event-listening',
        'basic/web-api',
        'basic/action-listening',
        'basic/action-respond',
        'basic/acknowledge',
        'basic/shortcuts',
        'basic/commands',
        'basic/creating-modals',
        'basic/updating-pushing-views',
        'basic/view-submissions',
        'basic/publishing-views',
        'basic/options',
        'basic/authenticating-oauth',
        'basic/socket-mode'
        ],
    },
    {
      type: 'category',
      label: 'Advanced concepts',
      items: [
        'advanced/error-handling',
        'advanced/authorization',
        'advanced/token-rotation',
        'advanced/conversation-store',
        'advanced/global-middleware',
        'advanced/listener-middleware',
        'advanced/context',
        'advanced/deferring-initialization',
        'advanced/logging',
        'advanced/custom-routes',
        'advanced/receiver',
      ],
    },
    {
      type: 'category',
      label: 'Deployments',
      items: [
        'deployments/aws-lambda',
        'deployments/heroku'
      ],
    },
    {
      type: 'category',
      label: 'Custom functions (Beta)',
      items: [
        'custom-functions/creating-custom-functions',
        'custom-functions/defining-custom-functions',
        'custom-functions/listening-to-custom-functions',
        'custom-functions/responding-to-interactivity',
      ],
    },
    {
      type: 'category',
      label: 'Workflow steps (Deprecated)',
      items: [
        'steps/steps-overview',
        'steps/creating-steps',
        'steps/adding-editing-steps',
        'steps/saving-steps',
        'steps/executing-steps',
      ],
    },
    {type: 'html', value: '<hr>'},
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorial/getting-started-http',
        'tutorial/hubot-migration',
        'tutorial/migration-v2',
        'tutorial/migration-v3'
      ],
    },
    {type: 'html', value: '<hr>'},
    'reference',
    {type: 'html', value: '<hr>'},
    'Changelog',
    {
      type: 'link',
      label: 'Code on GitHub',
      href: 'https://github.com/SlackAPI/bolt-js',
    },
    {
      type: 'link',
      label: 'Contributors Guide',
      href: 'https://github.com/SlackAPI/bolt-js/blob/main/.github/contributing.md',
    },

  ],
};

export default sidebars;
