name: Test site build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  test:
    name: Test site build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci  
        working-directory: ./docs

      - name: Build website
        run: npm run build
        working-directory: ./docs
